### ISSUE TITLE
Re-work how aws_auth is generated

### ISSUE THREAD

**Issue by tom-butler** [opendatacube/datacube-k8s-eks#141]
Instead of accepting a list of users / roles, and making them be able to assume into the user.clustername role we should just accept a list of roles and users and combine them in the aws_auth script.

This will simplify steps required to access the cluster after deploying it, instead of setting up custom roles in your aws profiles, you can just access the cluster directly with the role / user you are using. This also allows for more custom role logic x-account access etc to be possible. 

Example of the new set up:

```
users = {
  "user1" = "arn:aws:iam::012345678901:user/user1",
  "user1" = "arn:aws:iam::012345678901:user/user2"
}

roles = {
 "user-role" = "arn:aws:iam::012345678901:role/user-role"
}
```

Should create something like:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::012345678901:role/nodes.dea-sandbox
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::012345678901:role/user-role
      username: user-role
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::012345678901:user/user1
      username: user1
      groups:
        - system:masters
    - userarn: arn:aws:iam::012345678901:user/user2
      username: user2
      groups:
        - system:masters
````
